services:
  ai:
    build: ./ht-ai
    ports:
      - "30000:30000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    env_file:
      - ./ht-ai/.env

  server:
    build: ./ht-server
    ports:
      - "30001:30001"
    depends_on:
      - db
    env_file:
      - ./ht-server/.env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ht_db}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - TZ=Asia/Seoul
    volumes:
      - ./ht-db-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-ht_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
