spring:
  application:
    name: ht-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ht_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

kakao:
  client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
  client-secret: ${KAKAO_CLIENT_SECRET:your_kakao_client_secret}
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    use-root-path: true

server:
  forward-headers-strategy: native
  port: 30001

video-generation:
  nestjs:
    base-url: ${NESTJS_VIDEO_SERVICE_URL:http://localhost:30000}
    timeout: ${NESTJS_TIMEOUT:300000}

creatomate:
  api-key: ${CREATOMATE_API_KEY:}
  base-url: ${CREATOMATE_BASE_URL:https://api.creatomate.com/v1}

# Logging Configuration
logging:
  level:
    com.ht.htserver: DEBUG
    org.springframework.web: INFO
    org.springframework.transaction: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.web.reactive.function.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.stat: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] [%X{traceId:-},%X{spanId:-}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] [%X{traceId:-},%X{spanId:-}] - %msg%n"
  file:
    name: logs/ht-server.log
    max-size: 100MB
    max-history: 30

# Management endpoints for debugging
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always